server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.161.129:3306/majiang?characterEncoding=UTF8
  redis:
    host: 192.168.161.129
    jedis:
      pool:
        max-active: 10
        max-idle: 10
  rabbitmq:
    host: 192.168.161.129
    username: root
    password: root
    virtual-host: mj
    # 手动提交消息
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
    template:
      #重试参数
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
    #发送确认
    publisher-returns: true
    publisher-confirm-type: CORRELATED
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: xxp408395920
  expiration: 86400000
  header: Authentication
