server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.161.129:3306/majiang?characterEncoding=UTF8
  redis:
    host: 192.168.161.129
    jedis:
      pool:
        max-active: 10
        max-idle: 10
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: xxp408395920
  expiration: 3600000
  header: Authentication
